services:
  app:
    build: .  
    ports:
      - "8001:8001"
    volumes:
      - ./:/app    
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - POSTGRES_APPLICATION_NAME=Event Manager
      - POSTGRES_POOL_SIZE=10
      - POSTGRES_POOL_MAX_OVERFLOW=20
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
      - TEST_SYNC_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/test_db
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres:16
    ports: 
    - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
