services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sh
    # entrypoint: /docker-entrypoint-initdb.d/init-keycloak-db.sh
    # entrypoint: ["./init-keycloak-db.sh", "postgres"]
    command: ["-c", "shared_buffers=256MB"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
      - "8443:8443"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./support/keycloak-dev/realms:/realms

  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - POSTGRES_APPLICATION_NAME=Event Manager
      - POSTGRES_POOL_SIZE=10
      - POSTGRES_POOL_MAX_OVERFLOW=20
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5433/test_db
      - TEST_SYNC_DATABASE_URL=postgresql+psycopg2://postgres:postgres@localhost:5433/test_db
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  keycloak-data:
