services:
  app:
    build: .  
    ports:
      - "8000:8000"
    volumes:
      - ./:/app    
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
      - POSTGRES_DISABLE_JIT=true
      - POSTGRES_APPLICATION_NAME=EventManager
      - POSTGRES_POOL_SIZE=10
      - POSTGRES_POOL_MAX_OVERFLOW=20
    depends_on:
      - db
    
  db:
    image: postgres:16
    ports: 
    - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
